version: 2
registries:
  wex-github:
    type: git
    url: https://github.com
    username: ${{secrets.WEX_GITHUB_USERNAME}}
    password: ${{secrets.WEX_GITHUB_PASSWORD}}
updates:
- package-ecosystem: bundler
  directory: "/"
  insecure-external-code-execution: allow
  registries:
  - wex-github
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  # Dependabot is currently failing to pull gems hosted outside of RubyGems
  # We need to ignore these gems for now so that dependabot does proceed with updating the other gems
  ignore:
  - dependency-name: "waste_exemptions_engine"
  - dependency-name: airbrake
    versions:
    - "< 8"
    - ">= 7.a"
