version: 2
registries:
  wex-github:
    type: git
    url: https://github.com
    username: ${{secrets.WEX_GITHUB_USERNAME}}
    password: ${{secrets.WEX_GITHUB_PASSWORD}}
updates:
- package-ecosystem: bundler
  directory: "/"
  insecure-external-code-execution: allow
  registries:
  - wex-github
  schedule:
    interval: daily
  target-branch: dependabot-test
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
